spring:
  profiles:
    active: dev
---
server:
  port: 1111
#spring的配置
spring:
  application:
    name: spring-cloud-dev
    profiles: dev

#eureka的配置
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8848/eureka/

---
server:
  port: 2222
#spring的配置
spring:
  application:
    name: spring-cloud-test
    profiles: test

#eureka的配置
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8848/eureka/